language: python
python:
  - "3.6"
dist: trusty
addons:
  chrome: stable
before_install:
  - wget -qO -O tmp.zip http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip && unzip tmp.zip /usr/bin/
install:
  - pip install -r requirements.txt
script: 
  - python test_jietu.py
